build-plugin:
    cd plugins && sh build-all.sh

build-nsjail:
    cd nsjail-sys/nsjail && make

prepare:
    mkdir -p temp
    mkdir -p log
    touch log/sandbox.log
    touch log/nsjail.log

test:
    rm -rf temp/* 
    cargo test --target-dir sudo-target -- --nocapture

run:
    rm -rf temp/* 
    cargo run --target-dir sudo-target
