build-plugin:
    cd plugins && sh build-all.sh

build-nsjail:
    cd nsjail-sys/nsjail && make

prepare:
    mkdir -p .temp
    mkdir -p log

clean:
    sudo rm -rf .temp/* 
    cargo clean

test:
    sudo rm -rf .temp/* 
    cargo test --jobs 1 --no-fail-fast

run:
    sudo rm -rf .temp/* 
    cargo run
