services:
  backend:
    image: ghcr.io/mdcpp/mdoj/backend:staging
    volumes:
      - ./backend_config:/config
      - ./database:/database
    networks:
      - backend
      - judger
    ports:
      - 8081:8081
  judger:
    container_name: judger
    # you can actually turn this off if you setup the cgroup properly(user of the container should own the cgroup)
    privileged: true
    image: ghcr.io/mdcpp/mdoj/judger:staging
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - ./judger_config:/config
      - ./plugins:/plugins
    tmpfs:
      - /.temp
    networks:
      - judger
networks:
  judger:
  backend: