help:
    just --list


release-docker:

release:
    cargo build
    
setup-backend:
    cd ../docker/dev && sudo docker compose --profile migration up
    cd ../docker/dev && sudo docker compose --profile frontend-dev up

run:
    cargo leptos serve

dev:
    cargo leptos watch

fmt:
    cargo fmt
    leptosfmt ./**/*.rs
