release-docker:
    just prepare
    just release
    cp ../proto/*.proto .
    cp ../Cargo.toml ws-Cargo.toml
    docker build . -t mdoj-frontend

release:
    cargo build
    
prepare:

run:
    cargo leptos serve

dev:
    cargo leptos watch