# dev-migrate:
#     rm -rf backend.sqlite
#     touch backend.sqlite
#     DATABASE_URL=sqlite://backend.sqlite sea-orm-cli migrate refresh
#     sea-orm-cli generate entity -u sqlite://backend.sqlite -o entities

# prepare:
#     openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname"
#     touch backend.sqlite
release-docker:
    just prepare
    just release
    cp ../proto/*.proto .
    cp ../cert/*.pem .
    docker build . -t mdoj-gateway

release:
    cargo build
    
prepare:
    

run:
    cargo leptos serve

dev:
    cargo leptos watch