# dev-migrate:
#     rm -rf backend.sqlite
#     touch backend.sqlite
#     DATABASE_URL=sqlite://backend.sqlite sea-orm-cli migrate refresh
#     sea-orm-cli generate entity -u sqlite://backend.sqlite -o entities

prepare:
    mkdir -p database
    mkdir -p config
    sea-orm-cli migrate -u sqlite://database/backend.sqlite?mode=rwc

release-docker:
    just prepare
    cp ../proto/*.proto .
    cp ../cert/*.pem .
    docker build . --build-arg ARCH=$(uname -m) -t mdoj-backend

run:
    cargo run