# dev-migrate:
#     rm -rf backend.sqlite
#     touch backend.sqlite
#     DATABASE_URL=sqlite://backend.sqlite sea-orm-cli migrate refresh
#     sea-orm-cli generate entity -u sqlite://backend.sqlite -o entities

regen-database:
    rm database/*
    sea-orm-cli migrate -u sqlite://database/backend.sqlite?mode=rwc

prepare:
    mkdir -p database
    mkdir -p config
    sea-orm-cli migrate -u sqlite://database/backend.sqlite?mode=rwc

entity-codegen:
    rm database/*
    sea-orm-cli migrate -u sqlite://database/backend.sqlite?mode=rwc
    sea-orm-cli generate entity -u sqlite://database/backend.sqlite?mode=rwc -o src/pending

run:
    cargo run

ci-test:
    just prepare
    cargo test