# dev-migrate:
#     rm -rf backend.sqlite
#     touch backend.sqlite
#     DATABASE_URL=sqlite://backend.sqlite sea-orm-cli migrate refresh
#     sea-orm-cli generate entity -u sqlite://backend.sqlite -o entities

prepare:
    mkdir -p database
    mkdir -p config
    sea-orm-cli migrate -u sqlite://database/backend.sqlite?mode=rwc

entity-codegen:
    rm database/backend.sqlite
    sea-orm-cli migrate -u sqlite://database/backend.sqlite?mode=rwc
    sea-orm-cli generate entity -u sqlite://database/backend.sqlite?mode=rwc -o entity/src
    rm entity/src/mod.rs
    rm entity/src/prelude.rs

release-docker:
    just prepare
    sudo docker build  --build-arg ARCH=$(uname -m) -f ./Dockerfile -t mdoj-backend ..

run:
    cargo run

ci-test:
    just prepare
    cargo test