//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub mod prelude;

pub mod announcement;
pub mod chat;
pub mod contest;
pub mod education;
pub mod problem;
pub mod submit;
pub mod test;
pub mod token;
pub mod user;
pub mod user_contest;
