//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::announcement::Entity as Announcement;
pub use super::chat::Entity as Chat;
pub use super::contest::Entity as Contest;
pub use super::education::Entity as Education;
pub use super::problem::Entity as Problem;
pub use super::submit::Entity as Submit;
pub use super::test::Entity as Test;
pub use super::token::Entity as Token;
pub use super::user::Entity as User;
pub use super::user_contest::Entity as UserContest;
