//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::question_table::Entity as QuestionTable;
pub use super::question_user::Entity as QuestionUser;
pub use super::token_table::Entity as TokenTable;
pub use super::user_table::Entity as UserTable;
