//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "question_table")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: Option<String>,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::question_user::Entity")]
    QuestionUser,
}

impl Related<super::question_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuestionUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
