//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "group_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::group_table::Entity",
        from = "Column::Id",
        to = "super::group_table::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GroupTable,
    #[sea_orm(
        belongs_to = "super::user_table::Entity",
        from = "Column::Id",
        to = "super::user_table::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserTable,
}

impl Related<super::group_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupTable.def()
    }
}

impl Related<super::user_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserTable.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
