//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::group_table::Entity as GroupTable;
pub use super::group_user::Entity as GroupUser;
pub use super::question_table::Entity as QuestionTable;
pub use super::question_user::Entity as QuestionUser;
pub use super::session_table::Entity as SessionTable;
pub use super::token_table::Entity as TokenTable;
pub use super::user_table::Entity as UserTable;
