ci-run:
    echo start judger
    cd ../judger && just judger &
    echo start backend
    cd ../backend && just run &
    echo run testsuit
    cargo run
    echo kill all process
    kill $(jobs -p)