release-docker:
    MUSL_TARGET=$(uname -m)-linux-musl
    cd plugins/rlua-54 && sh ./build.sh
    cp ../proto/judger.proto .
    cp ../Cargo.toml ws-Cargo.toml
    docker build . --build-arg ARCH=$(uname -m) -t mdoj-judger

build-plugin:
    cd plugins && sh build-all.sh

release-plugin:
    just build-plugin
    cd plugins sh export-all.sh
    
build-nsjail:
    cd nsjail-docker && make nsjail-3.1
    cp nsjail-docker/output/*-linux-musl/nsjail-* .

prepare:
    just build-nsjail
    just build-plugin
    mkdir -p config plugins-out

feodra-deps:
    sudo dnf install protobuf-devel autoconf gettext libtool gcc libcap-devel systemd-devel yajl-devel libgcrypt-devel glibc-static libseccomp-devel python36 git

clean:
    sudo rm -rf .temp
    cargo clean
    docker images rm nsjail-3.1-$(uname -m)-linux-musl
    docker images rm protobuf-3.21.1-$(uname -m)-linux-musl
    docker images rm libnl-3.2.25-$(uname -m)-linux-musl
    docker images rm  musl-cross-make-$(uname -m)-linux-musl

test:
    sudo rm -rf .temp/*
    mkdir -p .temp
    cargo test --no-fail-fast -- --test-threads 1 

run:
    sudo rm -rf .temp/* 
    mkdir -p .temp
    cargo run

