release-docker:
    MUSL_TARGET=$(uname -m)-linux-musl
    just prepare
    cp ../proto/judger.proto .
    docker build . --build-arg ARCH=$(uname -m) -t mdoj-judger

build-plugin:
    cd plugins && sh build-all.sh
    
build-nsjail:
    cd nsjail-docker && make nsjail-3.1
    cp nsjail-docker/output/*-linux-musl/nsjail-* .

prepare:
    just build-nsjail
    just build-plugin

debian-deps:
    echo todo!()

feodra-deps:
    sudo dnf install protobuf-devel autoconf gettext libtool gcc libcap-devel systemd-devel yajl-devel libgcrypt-devel glibc-static libseccomp-devel python36 git

clean:
    sudo rm -rf .temp
    cargo clean
    docker images rm nsjail-3.1-$(uname -m)-linux-musl
    docker images rm protobuf-3.21.1-$(uname -m)-linux-musl
    docker images rm libnl-3.2.25-$(uname -m)-linux-musl
    docker images rm  musl-cross-make-$(uname -m)-linux-musl

test:
    sudo rm -rf .temp/*
    mkdir -p .temp
    cargo test --no-fail-fast -- --test-threads 1 

run:
    sudo rm -rf .temp/* 
    mkdir -p .temp
    cargo run

# podman-run:
#     # recreate cgroup of mdoj for normal user
#     sudo rm -rf /sys/fs/cgroup/mdoj
#     sudo cgcreate -a $USER -t $USER -g memory,cpu,cpuset:mdoj
#     # run podman
#     podman-compose up
