release-docker:
    just build-plugin
    docker build . -t mdoj-judger

build-plugin:
    cd plugins && sh build-all.sh

build-nsjail:
    cd nsjail && make

prepare:
    mkdir -p .temp
    mkdir -p log

debian-deps:
    echo todo!()

feodra-deps:
    sudo dnf install protobuf-devel autoconf gettext libtool gcc libcap-devel systemd-devel yajl-devel libgcrypt-devel glibc-static libseccomp-devel python36 git

clean:
    sudo rm -rf .temp/* 
    cargo clean

test:
    sudo rm -rf .temp/* 
    cargo test --no-fail-fast -- --test-threads 1 

run:
    sudo rm -rf .temp/* 
    cargo run
