name: staging

on:
  push:
    branches:
      - "staging"
    paths:
      - "**.rs"
      - .github/workflows/staging.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown, x86_64-unknown-linux-gnu
          components: clippy, rustfmt
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: Install Just
        uses: taiki-e/install-action@just
      - name: Install sea-orm-cli
        run: cargo install sea-orm-cli
      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings
      - name: Check
        run: cargo check
      - name: Run Backend Test
        run: cd backend && just ci-test
      - name: Run Frontend Test
        run: cargo test -p frontend
      - name: Run Judger test
        run: cd judger && just ci-test
      - name: Run testsuit
        run: cd testsuit && just ci-run
      - name: Build judger binary
        run: cargo install --target $(uname -m)-unknown-linux-musl --path judger
      - name: Build backend binary
        run: cargo install --target $(uname -m)-unknown-linux-musl --path backend
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create Draft Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: staging-${{ steps.date.outputs.date }}
          release_name: staging-${{ steps.date.outputs.date }}
          draft: true
          prerelease: false
      - name: upload judger
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: target/x86_64-unknown-linux-musl/release/judger
          asset_name: mdoj-judger
          asset_content_type: application/octet-stream
      - name: upload backend
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: target/x86_64-unknown-linux-musl/release/backend
          asset_name: mdoj-backend
          asset_content_type: application/octet-stream